[program]
title = "Fluentus"

[database]
name = "Fluentus"

[database.tables]
projects = "projects"

[ftl_field]
check = "check"

[table_column]
icon = ""
variable = "Variable"
translation = "Translation"

[colors]
highlight = "#D9AD2B"